### ISSUE TITLE
JDBCConnectionException

### ISSUE THREAD

**Issue by xyfigo** [meirwa/spring-boot-tomcat-mysql-app#1]
Hello @meirwa. When I start your meirwa/spring-boot-tomcat-mysql-app docker image with the flowing command：

 docker run -it -P meirwa/spring-boot-tomcat-mysql-app

I get a JDBCConnectionException：
Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Could not open connection

Do you know what happend? I think maybe your image do not have a mysql database in it.

**Comment by meirwah** [comment]
Hi @xyfigo ,

I modified this example, so it MUST include I running MySql container (with name “mysqldb”) in order for this app container to work.

I went with the approach of container per service here , since I wanted this to be part of a blog I wrote on the subject (that include linking containers)  : 
http://h30499.www3.hp.com/t5/Grounded-in-the-Cloud/Automate-Docker-and-enhance-your-DevOps-flows-with-HP-Operations/ba-p/6672688#.VPMAFvmsV1A

You will see there that you need to run : 

```
docker run --name mysqldb -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=boot -e MYSQL_USER=user -e MYSQL_PASSWORD=pass -d mysql
```

for MySql container to be up and running…

and for the app container :

```
docker run --name spring-boot-app --link mysqldb:mysql -e DB_URL=${DbContainerIP} -p 8080:8080 -d meirwa/spring-boot-tomcat-mysql-app
```

The port param you can get by using the cmd:

```
docker inspect --format='{{.NetworkSettings.IPAddress}}' mysqldb
```

of course you can modify that the image so it will also include the MySql DB, let me know if you want me to help you modify the example for that…
